build.gradle
gradle.properties
log-ballerina/Ballerina.toml
log-ballerina/build.gradle

Add stdlib dependency configs

---

.github/workflows/build-master.yml
README.md
log-ballerina/build.gradle
log-ballerina/src/log/natives.bal

Update readme file and remove public keyword

---

log-ballerina/src/integration_tests/tests/resources/log-messages/print_debug_test.bal
log-ballerina/src/integration_tests/tests/resources/log-messages/print_error_test.bal
log-ballerina/src/integration_tests/tests/resources/log-messages/print_info_test.bal
log-ballerina/src/integration_tests/tests/resources/log-messages/print_trace_test.bal
log-ballerina/src/integration_tests/tests/resources/log-messages/print_warn_test.bal
log-ballerina/src/integration_tests/tests/tests.bal
log-ballerina/src/log/natives.bal
log-ballerina/src/log/tests/json_log_formatter_test.bal

Migrate class and toString() change

---

log-native/src/main/java/org/ballerinalang/stdlib/log/Utils.java
log-test-utils/src/main/java/org/ballerinalang/stdlib/log/testutils/JsonLogFormatterTestUtils.java

Migrate jBallerina Runtime APIs

---

.github/workflows/pull-request.yml
log-ballerina/src/log/natives.bal

Update with isolated function changes

---

.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
build.gradle
log-ballerina/build.gradle

Update the release workflow

---

.github/workflows/build-master.yml
.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
build.gradle
gradle.properties
log-ballerina/build.gradle

Publish workflow

---

.github/workflows/build-master.yml
.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
README.md
log-ballerina/Ballerina.toml
log-native/build.gradle
log-native/src/main/java/module-info.java
log-test-utils/build.gradle
log-test-utils/src/main/java/module-info.java

> $Subject
Resolves https://github.com/ballerina-platform/module-ballerina-log/issues/14

Migrate to JDK11

---

log-native/src/main/java/module-info.java
log-native/src/main/java/org/ballerinalang/stdlib/log/AbstractLogFunction.java
log-native/src/main/java/org/ballerinalang/stdlib/log/Utils.java
log-test-utils/src/main/java/module-info.java
log-test-utils/src/main/java/org/ballerinalang/stdlib/log/testutils/JsonLogFormatterTestUtils.java

Refactor ballerina runtime api usages

Migrate ballerina runtime apis

---

.github/workflows/pull-request.yml
log-ballerina/src/log/natives.bal
log-native/src/main/java/org/ballerinalang/stdlib/log/AbstractLogFunction.java
log-native/src/main/java/org/ballerinalang/stdlib/log/Utils.java
log-test-utils/src/main/java/org/ballerinalang/stdlib/log/testutils/JsonLogFormatterTestUtils.java

Refactor module with Runtime API changes

---

log-ballerina/src/integration_tests/tests/resources/log-messages/print_debug_test.bal
log-ballerina/src/integration_tests/tests/resources/log-messages/print_error_test.bal
log-ballerina/src/integration_tests/tests/resources/log-messages/print_info_test.bal
log-ballerina/src/integration_tests/tests/resources/log-messages/print_trace_test.bal
log-ballerina/src/integration_tests/tests/resources/log-messages/print_warn_test.bal
log-ballerina/src/log/natives.bal

Mark log API functions as isolated

---

log-ballerina/src/integration_tests/tests/resources/log-messages/print_debug_test.bal
log-ballerina/src/integration_tests/tests/resources/log-messages/print_error_test.bal
log-ballerina/src/integration_tests/tests/resources/log-messages/print_info_test.bal
log-ballerina/src/integration_tests/tests/resources/log-messages/print_trace_test.bal
log-ballerina/src/integration_tests/tests/resources/log-messages/print_warn_test.bal

Update test cases with isolated function inputs

---

log-ballerina/natives.bal
log-integration-tests/tests/tests.bal

Update log output format to LogFmt

---

log-ballerina/natives.bal
log-integration-tests/tests/resources/log_level_test.bal
log-integration-tests/tests/tests.bal

Add support to pass function pointers

---

log-ballerina/natives.bal

Refactor code

---

build.gradle
gradle.properties
log-integration-tests/Ballerina.toml
log-integration-tests/build.gradle
log-integration-tests/tests/tests.bal

Change system module dependency to os

---

build.gradle
gradle.properties
log-ballerina/Ballerina.toml
log-ballerina/build.gradle
log-ballerina/tests/json_log_formatter_test.bal
log-integration-tests/Ballerina.toml
log-integration-tests/build.gradle
log-integration-tests/tests/tests.bal

Replace usages of stringutils

---

log-ballerina/build.gradle
log-integration-tests/build.gradle

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Update ballerina command to bal command

---

build.gradle
gradle.properties
log-native/build.gradle
log-native/src/main/java/org/ballerinalang/stdlib/log/AbstractLogFunction.java
log-native/src/main/java/org/ballerinalang/stdlib/log/Utils.java
log-test-utils/build.gradle
log-test-utils/src/main/java/org/ballerinalang/stdlib/log/testutils/JsonLogFormatterTestUtils.java

Enable checkstyle and spotbugs

---

log-ballerina/natives.bal
log-ballerina/tests/json_log_formatter_test.bal

Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …

Change the name of the `java` langlib module to `jballerina.java`

---

log-integration-tests/Ballerina.toml
log-integration-tests/Dependencies.toml
log-integration-tests/build.gradle

Fixes ballerina-platform/ballerina-lang#27988

Add Dependencies.toml

---

gradle.properties

Bump module version

---

.github/workflows/build-master.yml
.github/workflows/pull-request.yml
log-ballerina/build.gradle

Enable publishing of code coverage

---

log-ballerina/build.gradle

Avoid running tests twice when publishing

---

log-ballerina/natives.bal
log-ballerina/tests/log_test.bal
log-integration-tests/tests/resources/Config.toml
log-integration-tests/tests/tests.bal
log-native/src/main/java/org/ballerinalang/stdlib/log/AbstractLogFunction.java
log-native/src/main/java/org/ballerinalang/stdlib/log/Utils.java

> $Subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/901

Add support for json format configurability

---

README.md
log-ballerina/Package.md

Change the BBE URL links as /swan-lake/learn->/learn

---

README.md
log-ballerina/Package.md

Rename module to package in Readme.md and Package.md

---

.github/workflows/publish-release.yml
build.gradle
gradle.properties
log-ballerina/build.gradle
log-integration-tests/build.gradle

Enable Publishing to Ballerina Central on Release

---

log-ballerina/natives.bal
log-ballerina/tests/json_log_formatter_test.bal
log-integration-tests/tests/resources/Config.toml
log-test-utils/src/main/java/org/ballerinalang/stdlib/log/testutils/JsonLogFormatterTestUtils.java

Update json configuration output_format -> format

---

gradle.properties
log-integration-tests/tests/tests.bal

Bump lang version and improve test cases

---

build.gradle
log-ballerina/build.gradle

Re-order build tasks to enable publishing to central

---

log-ballerina/build.gradle

Fix ballerina push not working

---

.github/workflows/build-master.yml
.github/workflows/pull-request.yml
log-ballerina/build.gradle

Remove publishing exec artifacts and archiving test json

---

log-ballerina/build.gradle
log-integration-tests/build.gradle

> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763

Add extracted bala in the zip artifact

---

README.md

Reverts ballerina-platform/module-ballerina-log#86

Revert "Add codecov badge to README"

---

README.md

Add codecov label to README

---

log-ballerina/build.gradle

> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032

Add -c flag to build command

---

build.gradle

> Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1082

Remove invalid dependency

---

log-native/src/main/java/org/ballerinalang/stdlib/log/AbstractLogFunction.java
log-native/src/main/java/org/ballerinalang/stdlib/log/Utils.java

Remove unnecessary BLogManager dependencies

---

log-integration-tests/tests/resources/config/format/project/Config.toml
log-integration-tests/tests/tests.bal
log-native/src/main/java/org/ballerinalang/stdlib/log/AbstractLogFunction.java

> Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1154

Fix missing quote in module name when format is json

---

log-integration-tests/tests/tests_json.bal
log-integration-tests/tests/tests_logfmt.bal

Update env var property BALCONFIGFILE -> BAL_CONFIG_FILES

---

log-integration-tests/build.gradle
log-integration-tests/tests/Config.toml

Enable integration tests in windows

---

log-integration-tests/build.gradle

Strip stdlib dependency version in integration tests

---

 changelog.md
.github/workflows/central-publish.yml
README.md
log-ballerina/build.gradle

Move Ballerina build, test and publish into a single task

---

gradle.properties
log-ballerina/natives.bal

Fix the parameter order

---

codecov.yml
log-ballerina/natives.bal
log-ballerina/tests/Config.toml
log-ballerina/tests/log_test.bal
log-native/src/main/java/org/ballerinalang/stdlib/log/Utils.java
log-test-utils/src/main/java/org/ballerinalang/stdlib/log/testutils/utils/OSUtils.java

Add unit tests and improve test coverage

---

log-ballerina/tests/log_test.bal
log-integration-tests/tests/tests_logfmt.bal
log-native/src/main/java/org/ballerinalang/stdlib/log/Utils.java

Remove trailing space after INFO and WARN in log message

---

log-ballerina/build.gradle

Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381

Set flag to enable Jacoco Coverage XML generation

---

README.md
log-ballerina/Module.md
log-ballerina/Package.md
log-ballerina/natives.bal

Improve API Docs and add Package.MD file

---

build-config/checkstyle/build.gradle
build.gradle
gradle.properties
log-ballerina/build.gradle
log-integration-tests/build.gradle

Standardize build script of Ballerina module

 Apply Gradle Ballerina plugin for Ballerina module build script

---

gradle.properties
log-ballerina/build.gradle

Bump ballerina plugin version

---

log-ballerina/build.gradle

Remove overriding testCoverageParam and use the value from the gradle plugin.

Remove overriding testCoverageParam

---

gradle.properties
log-integration-tests/tests/tests_invalid_level.bal
log-integration-tests/tests/tests_json.bal
log-integration-tests/tests/tests_logfmt.bal
log-native/build.gradle

Update expected console output in integration tests

---

.github/workflows/build-timestamped-master.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
build.gradle
log-ballerina/Package.md

Related to ballerina-platform/ballerina-release#547 and ballerina-platform/ballerina-standard-library#1462

Update Package.md and workflow config

---

log-ballerina/natives.bal
log-integration-tests/build.gradle
log-integration-tests/tests/process.bal
log-integration-tests/tests/resources/config/json/observability-project/Config.toml
log-integration-tests/tests/resources/config/logfmt/observability-project/Config.toml
log-integration-tests/tests/resources/samples/observability-project/Ballerina.toml
log-integration-tests/tests/resources/samples/observability-project/main.bal
log-integration-tests/tests/tests_json.bal
log-integration-tests/tests/tests_logfmt.bal
log-test-utils/src/main/java/org/ballerinalang/stdlib/log/testutils/nativeimpl/Exec.java
log-test-utils/src/main/java/org/ballerinalang/stdlib/log/testutils/nativeimpl/Stdout.java

$Subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1342

Add observability span context to logs

---

 changelog.md

Update changelog related to beta2

---

log-ballerina/natives.bal
log-ballerina/tests/log_test.bal
log-native/src/main/java/org/ballerinalang/stdlib/log/Utils.java

$Subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1592

Re-write printing in logfmt format in Ballerina

---

settings.gradle

Refactor Settings.gradle file

---

gradle.properties
integration-tests/tests/tests_json.bal
integration-tests/tests/tests_logfmt.bal

Update test cases with language changes

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
build.gradle
gradle.properties
integration-tests/Ballerina.toml
integration-tests/build.gradle
settings.gradle

https://github.com/ballerina-platform/ballerina-lang/issues/32190

Update package with the latest package resolution changes

---

.github/workflows/publish-release.yml

$Subject
Related https://github.com/ballerina-platform/module-ballerina-log/pull/314

Update scan-ref path

---

ballerina/Dependencies.toml
gradle.properties
integration-tests/Dependencies.toml

Bump ballerina lang dependency version

---

integration-tests/tests/tests_invalid_level.bal
integration-tests/tests/tests_json.bal
integration-tests/tests/tests_logfmt.bal

Fix unused variable warning

---

gradle.properties
integration-tests/Dependencies.toml
integration-tests/build.gradle
integration-tests/tests/tests_logfmt.bal

https://github.com/ballerina-platform/ballerina-standard-library/issues/2396

Bump gradle plugin version

---

integration-tests/tests/tests_json.bal

Print integration tests output

---

.github/workflows/publish-release.yml
integration-tests/tests/tests_json.bal

Add a clean task to clean unnecessary artefacts

---

ballerina/natives.bal
docs/spec/spec.md

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2347

Add log module specification

---

ballerina/natives.bal
integration-tests/build.gradle
integration-tests/tests/resources/samples/file-write-output/single-file/set-output-file-negative.bal
integration-tests/tests/tests_json.bal
integration-tests/tests/tests_logfmt.bal
integration-tests/tests/tests_negative.bal

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2350
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2349

Add negative tests and improve code quality

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties
integration-tests/Dependencies.toml

Related to - https://github.com/ballerina-platform/ballerina-standard-library/issues/2503
stdlibIoVersion=1.2.0-20211217-111800-6a26ebc
stdlibRegexVersion=1.2.0-20211217-111900-3d6286b

Upgrade the module and distribution versions

---

ballerina/natives.bal

Add stack trace as an optional param in print functions

---

.github/workflows/process-load-test-result.yml
.github/workflows/trigger-load-tests.yml
load-tests/log/deployment/ingress.yaml
load-tests/log/deployment/kustomization.yaml
load-tests/log/results/summary.csv
load-tests/log/scripts/http-get-request.jmx
load-tests/log/scripts/run.sh
load-tests/log/src/Ballerina.toml
load-tests/log/src/Cloud.toml
load-tests/log/src/app.bal

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2366

Add load test for log module

---

ballerina/natives.bal

Improve API docs

---

integration-tests/build.gradle

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2653

Improve integration test build scripts

---

docs/spec/spec.md

Fix formatting issue in spec

---

.github/workflows/process-load-test-result.yml
.github/workflows/trigger-load-tests.yml
ballerina/Ballerina.toml
ballerina/Dependencies.toml
integration-tests/Dependencies.toml

https://github.com/ballerina-platform/ballerina-standard-library/issues/2697

Improve load test workflows

---

gradle.properties

Update observe module dependency version

---

ballerina/CompilerPlugin.toml
ballerina/build.gradle
ballerina/natives.bal
ballerina/tests/log_test.bal
build-config/resources/CompilerPlugin.toml
compiler-plugin/build.gradle
compiler-plugin/src/main/java/io.ballerina.stdlib.log.plugin/LogCodeModifier.java
compiler-plugin/src/main/java/io.ballerina.stdlib.log.plugin/LogCompilerPlugin.java
compiler-plugin/src/main/java/module-info.java
gradle.properties
native/src/main/java/io/ballerina/stdlib/log/Utils.java
settings.gradle

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2860
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2858

Add code modifier support to get module name

---

 changelog.md

Update log module changelog

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/natives.bal
compiler-plugin/src/main/java/io.ballerina.stdlib.log.plugin/LogCompilerPlugin.java

Remove code modifier support

---

 changelog.md

Update changelog with 2.4.1 release changes

---

.github/workflows/build-timestamped-master.yml

Ignore load test results in build

---

.github/workflows/build-with-bal-test-native.yml
README.md
ballerina/Dependencies.toml
gradle.properties
integration-tests/build.gradle

https://github.com/ballerina-platform/ballerina-standard-library/issues/3316

Add Build with bal test native workflow

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517

Update versions for type-reference-support

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Add type reference support

---

 changelog.md
gradle.properties

Update regex dependency to the latest version

---

gradle.properties

Update regex dependency version

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build.gradle
gradle.properties
integration-tests/tests/tests_json.bal
integration-tests/tests/tests_logfmt.bal
integration-tests/tests/tests_negative.bal

$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4382

Remove regex package usages

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Reverts ballerina-platform/module-ballerina-log#883

Revert "Update lang and distribution versions"

---

.github/workflows/build-with-bal-test-graalvm.yml
README.md
gradle.properties
integration-tests/build.gradle

$Subject
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/4548

Incoperate native build command change

---

.github/workflows/build-timestamped-master.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml
README.md
build-config/checkstyle/build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
integration-tests/Ballerina.toml
integration-tests/build.gradle
settings.gradle

Migrate to Java 17

---

ballerina/natives.bal

Add parameter types for Java String replace method interop

---

docs/proposals/dynamic-loglevel-setup.md

related to :[4633](https://github.com/ballerina-platform/ballerina-standard-library/issues/4633)

Add proposal for dynamic log level changes

---

ballerina/natives.bal

Specify parameter type for string replace method interop call

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties
integration-tests/Ballerina.toml

Bump minor version and update distribution

---

.github/workflows/build-timestamped-master.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml

Update Java version to 17.0.7 for workflows

---

gradle.properties

Change lang version to timestamp artifact

---

.github/workflows/build-timestamped-master.yml
.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/process-load-test-result.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml
README.md
ballerina/Ballerina.toml
build-config/resources/Ballerina.toml
compiler-plugin/build.gradle
gradle.properties
integration-tests/Ballerina.toml
native/build.gradle
test-utils/build.gradle

Migrate to Java 21

---

gradle.properties

[Java 21] Update observe module versions

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

This PR contains automated changes for update 12 release.

[Automated] Prepare for Update 12 release

---

 changelog.md
.gitignore
ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
build-config/resources/CompilerPlugin.toml
codecov.yml
compiler-plugin-tests/build.gradle
compiler-plugin-tests/src/test/java/io/ballerina/stdlib/log/compiler/staticcodeanalyzer/ProcessOutputGobbler.java
compiler-plugin-tests/src/test/java/io/ballerina/stdlib/log/compiler/staticcodeanalyzer/StaticCodeAnalyzerTest.java
compiler-plugin-tests/src/test/resources/static_code_analyzer/ballerina_packages/rule1/Ballerina.toml
compiler-plugin-tests/src/test/resources/static_code_analyzer/ballerina_packages/rule1/Config.toml
compiler-plugin-tests/src/test/resources/static_code_analyzer/ballerina_packages/rule1/main.bal
compiler-plugin-tests/src/test/resources/static_code_analyzer/expected_output/rule1.json
compiler-plugin-tests/src/test/resources/testng.xml
compiler-plugin/build.gradle
compiler-plugin/src/main/java/io/ballerina/stdlib/log/compiler/LogCodeModifier.java
compiler-plugin/src/main/java/io/ballerina/stdlib/log/compiler/LogCompilerPlugin.java
compiler-plugin/src/main/java/io/ballerina/stdlib/log/compiler/staticcodeanalyzer/LogRule.java
compiler-plugin/src/main/java/io/ballerina/stdlib/log/compiler/staticcodeanalyzer/LogStatementAnalyzer.java
compiler-plugin/src/main/java/io/ballerina/stdlib/log/compiler/staticcodeanalyzer/RuleFactory.java
compiler-plugin/src/main/java/io/ballerina/stdlib/log/compiler/staticcodeanalyzer/RuleImpl.java
compiler-plugin/src/main/java/io/ballerina/stdlib/log/compiler/staticcodeanalyzer/StaticCodeAnalyzer.java
compiler-plugin/src/main/java/module-info.java
compiler-plugin/src/main/resources/rules.json
gradle.properties
settings.gradle

Add scan tool

---

compiler-plugin-tests/src/test/java/io/ballerina/stdlib/log/compiler/staticcodeanalyzer/StaticCodeAnalyzerTest.java

Add a log for checking the scan tool pull status

---

docs/spec/spec.md

Fix typos in logging documentation
